/// <reference types="bun" />
// Evidence harness, run from separate /home/user/browser-check with Playwright.
// Not a project runtime/build dependency; no browser used for scraping.
import { chromium, expect } from '@playwright/test';
const browser = await chromium.launch({ headless:true, args:['--no-sandbox'] });
const page = await browser.newPage({ viewport:{width:1440,height:900} });
const errors: string[]=[]; page.on('pageerror',e=>errors.push(String(e)));
await page.goto('http://localhost:3000');
await page.locator('input[data-checkbox="CGUS"]').waitFor({timeout:60000});
await expect(page.locator('#app-subtitle')).toHaveText('');
await expect(page.locator('#app-summary')).toBeHidden();
await page.locator('#ticker-count').hover(); await expect(page.locator('#app-summary')).toBeVisible();
await page.locator('#app-summary a').first().hover(); await expect(page.locator('#app-summary')).toBeVisible();
await expect(page.locator('#app-summary a[href="./api/capital-group/index.json"]')).toBeVisible();
await page.keyboard.press('Escape'); await expect(page.locator('#app-summary')).toBeHidden();
await page.locator('#theme-toggle').focus(); await page.locator('#ticker-count').focus(); await expect(page.locator('#app-summary')).toBeVisible();
await page.keyboard.press('Escape');
await page.locator('tr[data-ticker="CGUS"] td').nth(2).click();
await expect(page.locator('#app-subtitle')).toHaveText('');
await page.locator('[data-checkbox="CGUS"]').check();
await expect(page.locator('#app-subtitle')).toHaveText('1 selected: CGUS');
await page.locator('[data-checkbox="CGCP"]').check();
await expect(page.locator('#app-subtitle')).toHaveText('2 selected: CGCP, CGUS');
await page.locator('[data-checkbox="CGMU"]').check();
await expect(page.locator('#app-subtitle')).toHaveText('3 selected: CGCP, CGMU, CGUS');
await page.locator('[data-header-fund="CGUS"]').click();
await expect(page.locator('[data-header-fund="CGUS"]')).toHaveClass(/underline/);
await expect(page.locator('#app-subtitle')).toHaveText('3 selected: CGCP, CGMU, CGUS');
await page.reload(); await expect(page.locator('#app-subtitle')).toHaveText('3 selected: CGCP, CGMU, CGUS');
await page.locator('#theme-toggle').click();
await page.waitForTimeout(800);
await page.screenshot({path:'/home/user/Capital-Group/evidence/ui-desktop.png'});
await page.setViewportSize({width:375,height:812});
await page.locator('#ticker-count').click(); await expect(page.locator('#app-summary')).toBeVisible();
const box=await page.locator('#app-summary').boundingBox(); if(!box || box.x<0 || box.x+box.width>376) throw new Error('Panel outside narrow viewport '+JSON.stringify(box));
await page.screenshot({path:'/home/user/Capital-Group/evidence/ui-mobile.png'});
await page.keyboard.press('Escape');
await page.setViewportSize({width:1440,height:900});
await page.locator('[data-tab="All"]').click();
await page.locator('[data-checkbox="CGUS"]').uncheck();
await expect(page.locator('#app-subtitle')).toHaveText('2 selected: CGCP, CGMU');
await page.locator('[data-blacklist="CGCP"]').click();
await expect(page.locator('#app-subtitle')).toHaveText('1 selected: CGMU');
await page.locator('#reset-btn').click();
await expect(page.locator('#app-subtitle')).toHaveText('');
await page.locator('#file-input').setInputFiles({name:'CGUS.xml',mimeType:'text/xml',buffer:Buffer.from('<nportRegDoc><genInfo><regName>Capital Group Equity ETF Trust</regName><seriesName>Capital Group Core Equity ETF</seriesName><seriesId>S000000001</seriesId><repPdDate>2026-09-24</repPdDate></genInfo><invstOrSec><name>Apple Inc</name><cusip>037833100</cusip><balance>100</balance><valUSD>20000</valUSD><pctVal>100</pctVal><assetCat>EC</assetCat></invstOrSec></nportRegDoc>')});
await expect(page.locator('#app-subtitle')).toHaveText('');
await page.locator('[data-checkbox="CGUS"]').check();
await expect(page.locator('#app-subtitle')).toHaveText('1 selected: CGUS');
await page.locator('#ticker-count').hover(); await expect(page.locator('#app-summary')).toBeVisible();
const touch = await browser.newContext({viewport:{width:375,height:812},hasTouch:true,isMobile:true});
const phone = await touch.newPage(); await phone.goto('http://localhost:3000'); await phone.locator('[data-checkbox="CGUS"]').waitFor();
await phone.locator('#ticker-count').tap(); await expect(phone.locator('#app-summary')).toBeVisible();
await phone.locator('#app-summary a').first().tap({trial:true}); await touch.close();
console.log(JSON.stringify({passed:['zero/some/all selections','sorted selected links','row click does not select','active link does not deselect','restored selection','hover to interactive panel','API link retained','keyboard focus and Escape','theme toggle','375px click panel bounds','deselection/blacklist/clear','uploaded N-PORT header context','touch panel and link access'], errors},null,2));
if(errors.length)throw new Error(errors.join('\n'));
await browser.close();
